
import { GoogleGenAI, GenerateContentResponse } from "@google/genai";
import { ImageData, StudioAction } from "../types";

export class GeminiService {
  private ai: GoogleGenAI;

  constructor() {
    this.ai = new GoogleGenAI({ apiKey: process.env.API_KEY || '' });
  }

  async processFashionAction(
    action: StudioAction,
    baseImage: ImageData,
    garmentImage: ImageData | null,
    settings: { lighting: string; pose: string; garmentDesc: string; beauty: string; aspectRatio: string }
  ): Promise<string> {
    const model = 'gemini-2.5-flash-image';
    
    let prompt = "";
    const parts: any[] = [
      {
        inlineData: {
          data: baseImage.base64,
          mimeType: baseImage.mimeType
        }
      }
    ];

    if (garmentImage && (action === 'TRY_ON' || action === 'GHOST_MANNEQUIN')) {
      parts.push({
        inlineData: {
          data: garmentImage.base64,
          mimeType: garmentImage.mimeType
        }
      });
    }

    const beautyModifier = `Apply ${settings.beauty} skin retouching and facial enhancement.`;

    switch (action) {
      case 'TRY_ON':
        prompt = `Perform a high-end virtual try-on. Replace the clothing of the person in the primary image with the garment shown in the second image (or described as: ${settings.garmentDesc}). ${beautyModifier} Maintain the person's identity and pose. Professional fashion photography quality. Lighting: ${settings.lighting}. Pose context: ${settings.pose}.`;
        break;
      case 'GHOST_MANNEQUIN':
        prompt = `Create a ghost mannequin effect. Remove the person from the image, leaving only the clothes. The clothes should appear 3D and hollow, showing the inside lining where the person's skin was previously visible. High quality commercial product shot.`;
        break;
      case 'RELIGHT':
        prompt = `Maintain the person and clothing perfectly, but change the environmental lighting to: ${settings.lighting}. ${beautyModifier} Ensure shadows and highlights accurately reflect this new lighting setup. High fashion editorial style.`;
        break;
      case 'REPOSE':
        prompt = `Maintain the person's face and the specific clothing, but modify the pose to: ${settings.pose}. Keep the lighting as ${settings.lighting}. ${beautyModifier} High-end commercial look.`;
        break;
      case 'BEAUTY':
        prompt = `Focus exclusively on high-end beauty retouching. Mode: ${settings.beauty}. Enhance skin texture, remove minor blemishes while maintaining realism, optimize facial lighting, and sharpen eye/lip details. Maintain the original pose, clothing, and background. Style: High-fashion editorial.`;
        break;
    }

    parts.push({ text: prompt });

    const config: any = {};
    if (settings.aspectRatio !== "Default") {
      config.imageConfig = {
        aspectRatio: settings.aspectRatio
      };
    }

    const response = await this.ai.models.generateContent({
      model: model,
      contents: { parts },
      config: config
    });

    let resultUrl = "";
    if (response.candidates?.[0]?.content?.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          resultUrl = `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
          break;
        }
      }
    }

    if (!resultUrl) {
        throw new Error("No image was generated by the model.");
    }

    return resultUrl;
  }

  async analyzeGarment(image: ImageData): Promise<string> {
    const model = 'gemini-3-flash-preview';
    const response = await this.ai.models.generateContent({
      model: model,
      contents: {
        parts: [
          { inlineData: { data: image.base64, mimeType: image.mimeType } },
          { text: "Describe this garment in detail for an AI image generator. Mention fabric, cut, color, pattern, and unique details. Be concise." }
        ]
      }
    });
    return response.text || "A stylish garment.";
  }
}
